### ISSUE TITLE
How can I remove the "Leech Tag" that is made by default + an extra question

### ISSUE THREAD

**Issue by chrisnerio** [glutanimate/hierarchical-tags#2]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

![Screen Shot 2020-04-16 at 6 00 38 AM](https://user-images.githubusercontent.com/63787525/79448771-a43dc900-7fa7-11ea-8415-101513add23e.png)

#### Is there any way to remove that "leech" tag from the sidebar? Just an extra question- how can you remove the little tag icons that you also see in the picture. I remember the older version I believe "Hierarchical Tags 20 21" did not have them. Thank you!!

**Comment by glutanimate** [comment]
Hi Chris! I'm afraid that's how Anki behaves in 2.1 by default. If you remove the add-on you should see the same exact behavior (icons and leech tag). It would be possible to modify that behavior with an add-on, but I'd like Hierarchical Tags 2 to remain as close to the defaults as possible.

Hope that at least explains the situation!

**Comment by chrisnerio** [comment]
Thank you for the speedy response!
