### ISSUE TITLE
Addon doesn't work

### ISSUE THREAD

**Issue by maksovnik** [glutanimate/hierarchical-tags#4]
Addon does nothing, Anki Version 2.1.26.
Addon is not disabled in addons menu and I disabled all other addons that could be interfering.

The addon doesnt seem to do anything, right clicking on anything in the bar on browser doesnt do anything. My mouse changes to a loading icon for 0.5 seconds and nothing happens.

**Comment by glutanimate** [comment]
Hi Maks,

There's a bit of a misunderstanding here: The only thing Hierarchical Tags does is make your tags hierarchical. That is, if you add a tag in the form of `parent::child`, `child` will appear nested under `parent` in the sidebar, like this:

```
> parent
  |_ child
```

The add-on does not add a right-click menu to the sidebar or any other features. For more advanced options like that you could check out [BetterTags](https://www.patreon.com/posts/bettertags-v1-0-33338657).

**Comment by maksovnik** [comment]
Hi thanks for the reply - sorry for that!, how do I set up tags that are
just random tags in my browser and move them to be a child of a parent?
